// SPDX-FileCopyrightText: Copyright (c) 2026 Logan Bussell
// SPDX-License-Identifier: WTFPL

namespace Imtui;

/// <summary>
/// Unique identifier for a widget in the immediate-mode UI system.
/// Generated by hashing a label against the current ID stack seed using
/// FNV-1a over UTF-16 code units.
/// </summary>
public readonly record struct WidgetID(int Value)
{
    /// <summary>
    /// The root seed used as the initial value for the ID stack.
    /// This is the FNV-1a 32-bit offset basis.
    /// </summary>
    public static readonly WidgetID Root = new(unchecked((int)0x811c9dc5));

    /// <summary>
    /// Hashes a string label with a seed to produce a new ID.
    /// </summary>
    public static WidgetID Hash(ReadOnlySpan<char> label, WidgetID seed)
    {
        uint hash = unchecked((uint)seed.Value);

        foreach (char c in label)
        {
            hash ^= c;
            hash *= 16777619;
        }

        return new WidgetID(unchecked((int)hash));
    }

    /// <summary>
    /// Hashes an integer value with a seed to produce a new ID.
    /// </summary>
    public static WidgetID Hash(int value, WidgetID seed)
    {
        uint hash = unchecked((uint)seed.Value);
        hash ^= unchecked((uint)value);
        hash *= 16777619;

        return new WidgetID(unchecked((int)hash));
    }
}
